name: Build and Publish LaTeX Document
on:
  workflow_run:
    workflows: ["Build LaTeX document"]
    types:
      - completed
    branches:
      - master  # Only trigger on completion of build_latex when changes are pushed to master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: root.tex
          args: -synctex=0 -interaction=nonstopmode --shell-escape -pdf -file-line-error

      - name: Save PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: root.pdf
          path: root.pdf

  publish_pdf:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download root.pdf artifact
        uses: actions/download-artifact@v3
        with:
          name: root.pdf
          path: ./

      - name: Publish PDF to gh-pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git switch -C gh-pages origin/gh-pages || git checkout --orphan gh-pages
          mv root.pdf longCV_GALLEGATI_andrea.pdf
          git add longCV_GALLEGATI_andrea.pdf
          git commit -m "Update PDF on GitHub Pages"
          git push --force origin gh-pages
